#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Shrey Shah (21BCP335)

# Short bio or description (displayed in the header)
description: Docker 3 Tier Architecture

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOAAAADgCAMAAAAt85rTAAAAz1BMVEX///8klu0oUZ4kluwljOImabkkkecoTpwklu4oVKEoUJ0kl+0nYrIkmfEkkOaaq86BmsgnXascTp8mcMEkiN7y9flohbslg9cmdccnXq3Q2OknZbQmeMooV6Ulf9IcTZ87Y6rc4+8AkOzt8fiQpMy7x9/X3+3DzuMARZxOcLGxwdwgVKZ8lMTw8vhxjMAAPZimt9eezfZGa69hf7lXd7RDoe9lsfFyufPe7fyVxvS42PcALpQ/p+9ztvKXzfWPrNHM5fq63PgAIZGfvuKLncXpQowZAAANF0lEQVR4nO2cC3vaOhKGkXyVjAELE3PxBQKEW0oJJO05PWe3Pbv9/79pR7YBG2xDWjBJVm/6EJgYqs8ja2YkmUpFIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAI3jmtQ27doMsynC/vDqh3b92oSzIKmMaYpmkMa/wRXgX9wa1bdTkGz5TQEI1uIcHq1s26HN0+tWomQrqOYsw2Dhq3btbl6PaxYnJd0k6hTdmHEkhBYM2RkO7ICMk20j+eQMNwLRDnuchs9mof0YNmm9hI0prI7Fmy8dEEajuBbcPsdeQP6EHDiAWGHvyAAnce1D+qB83/Fw9+VIGG2cQ2UuNR9CMKRE6zhiTFR4bbrH3AQA+pmokkxDM20/xoqdpDH/eiVFvnP/Db9Om7SbbH9ZM0LOIp7RQWeSceHC6txWJB4OcAQrg5tBMOJnhL+Iy8Ew8+B/gQruakibwXgeCeajNFB9T00iYLTMqh6Z10UUYseVfFImQYuuPhTmgywn8cMFXV+ID4QP/0KDoelqLgBAvcgzIdxn3JDCMAlLMWhnpvFw90E5lgCsOEjl4RJsbWbFyOhkIY7qlIbtd01fVNiOWSHgrU5aaMwATea6soEgiB3kBNB0KEq54W+DBjEElu70TGO59DHVTrdCDd1ECNBwINR/NRzVNU5BJZDwWmUrWTBe+nJYNxKehPyhKSR+hBhzhI7lQTAnVHc3TV4gI9OeqiPNnW0bnl0jwgxLUwWz+UpSQH7kH9WKDJBdZigfpOIAKB5lkC+1hrmrKC8XpelpRsFluBtZ1AKxRIHZN7UE958GyB3Sm24IpFoDC47Rx/gQdNNdODZ3XRBiO+wRPXJmHPN53jzxBoFQsMPWjYuEjgw1rr1MJ4qfZocHfLsTTqojjZReNBxs8SCKOoeUbBW1/gZpQQ6HYHe7e8DMNR1O7YqKZAqHOtWCCyLdDca+qGz4NiKNCFnilZfOJXOTHxO9xofJI4zJBM2WOzG3bSMA4inoep4cMuk0ma7DDQS+ErKTIXdtGHNe2Zu3UaBS9uuBDFcEcKy9hde8CD1ZqOUibQbO5NvOYt9ODEg0tV2r5dxrh/u2gI1YQLiSgQPkhIbRLi+ZGJv0aRybLDA1BogB+laPlsHsAQtT8/TRqMylHTms+O61pC4xqWxGUfPFC8K3L5A43thEQPUdVLvIPPuttGvHqg1fYVCqR8eF2OwPGCZZSy5MiQaTt+Hz34rKAfKWyNmJbQx909LWXTQmsECWI1ScfjDU2buMu8AxNgpUxVrvjoqCCKB60Go0mByKXTUtKZ1iPTHDVFDTqanTb5HracQxPp1NImlxIrbVHbOKhvBeKUQJ8E9VZ3vKrXR/XVuHs1b8J/rElRUa5HxatuWrgqRcNjuAAPJh4H1biyjUy7gjeqiHU4EsolbooiHYrKYlvbC6SJWQII9h5h0+k0CIEn69XwKiIjgaoPMdh2kK76KjLDyYiaX0OqAyYZhs8o0HMTciA3kx01CvRIhuNR9GZVjwTKvh59HrwZYv9W4CjQ1KQHbSsapDyAX8wssJbjKwT/SKBMIJ1UPMhfiBwJjKqJatXUEwUvryY6imQkqwk5WgBVwmSbC3ThWrP55/UsdS+wsgo0OSlQ9qiltH3fAXy/3YHhiS1ml6+FW48BjG4yacYCsR120axqQt+WS0Y6F5X25VIoEE5YJNBLChwzyGQTXVT1nZq6C/yoZrsdDbP+xVPUrQcjgfpOYE5FvxOYXQ9GAjM9GK9l7BUaycQIRgHTrCmEWpfupVxglgdfJ9A4LXDwzKxEpE9q29l8HNxdWF8YJlDiGizsopqDjudkkkvYBQJbPzFpZ6hKoFZxcPEE9VggyvNgquA1j69Bo1Ag76OdWpE+06dsc2l9oUApr4vmzMmgo0HGiAvegkGmUmkExS6E9NS7fHITDTI2bm4bJG8F4kMPoqyKHvNrMKrokx7EGQKHAcbJgfTAf1BgXqPAiAYZ1bWR7vj8iRoLDAO970CV58YFr1FzZR35EPttfzuzbbsQveHNpuOrsQdlVzJUV44+Lymw0sfYyr8AYQi9u1qg57natnLVeaAPA1Q4kuuGsavoeUJnGNEGyjhVCw8z4qNoZIKsDV5yk7kX+FDfeJCwqFniuP+qhM0uPhHVarU+8WQ7qmxRXL2qPNlG29I2NEFmbdkoLm+jv/BkW92beM3Lk20k7Y8CUxsEtj4NH0bWNGCYVOWs8MBPlwbevbD/hvP6CJhh7CkpOpAhWmkTr6DSpp4HR1WPjsKd9FFgeV4+9xdQk1Gq+Jn+00256WH2fOEBpnvHwkQ+c6U2LFx57cp/0bi6jWpZGv6iqaqYhsdtj6KRgdLIxFj43FJcNWOE0U1TdnsUB5fWV+9TrRwo8apNX04mnqEuDtQr7R6UFUEwv3CtNPyMiWLLZVBDoZT0mNLuKc2mUvX4CWC4/3jx4aUOQTcaJH+Nk29E22O4HgkdoHbCXfpQBTJvvbzG7RZ3rLOrzo7++6tjOlDO8+t/valPHq6ySrFh1Vo4mZnDBUTnfQSfDWlTb9SddAfDT9cQFwuEXGPfiJzwlGv/PZxrBPVDgZD9X6n5p2kmE7jrcMf4Vhg9U+G1ZRtQNvSvPem75AK396yUPco4JexKbDDILfN8le3Y9CHx7185N2YVL66+sjRinoOu3xsz9Tkau7v6sgQEeqe0vpn+b1Rw4PXXr+dT7PPVyyyJe7eeOAFS1ktJyrAlLKZP6OP115W6IPC3HSilmn7upym0jL1cgylt79qXWhTJF/MKcz66Y2mbMhYGp7S5a1yZYULt4WkpO0jCrSJSvLoenlqU/JVAyniW9TLnPKWtuk+xV8rK7jP2VPTqayhjADlHZILLT73ksGRENk615uLwyetGOd8nsAqob0rHo/gppPRzKcNcgN3B/ZI2GkKc6JmFzUpNoWxr89QfXz04qQoOSoiBIcMZ1lRdSowqcXMzEnDdePny9cuLoaP8IUeKInzxNe0Ttiltl+Eq0JzzzrtuPPFWDZ/us5t9TM5BDiHlbB0JmXi0aSbu8s/n/iuo4/s8vtyfd0ZyBJodzGal6asMZrQapaL68dxM6rXRqszXa3DiHy+7ObJfyA1Ml7IyN+C1HpknG8ezekfNv/+z0vWYNWm1Kk/nujALh2Cr1K3adUz840h47Jr7b5XVlJDZZlz59uv1o2Fb1KuX+pU6kz5Wzql4758qY4YJ/gsE/oYHC/daXoXhWvOKxtGtL/W/K63lNPh896nyr/vjP5+H6RI8LXsf+iSgynY9Sypo8f2/4djvcPn8ef96ZbG+plZaCpOgj71aKs7ntP3lR3j4jxx9Zyh2PGzd4LazekDdnHQtJVd/+fr07ekrBAmpyNP5+Bb2rj3Tm8Vgga3ifHSrUDe2S/O/guzh4PrzaBm0HsGFZzbynGmNfH1seQN5QHeNPbtAlOrYvz9z6oP/lrf6TrlRuH8ss5dKyLSbxDtXRl5PNx0L/Hezu1yGa2rZcZc7GD90W/Egdu32RWStY5ycwUBm2yO3818lvJuherhDjo8mqmNpmGHr+/2v5tYcA7ka9i6+Q/I1fNowqJrM3bihm0itOX6zSjDzNvUBJC/SwWR1JtmXqq1Agl1uAnrEYI2p68iqHu3qkP220oOuSbTPz+E973+cXQQeYTodjPs3v618FRDiWVa1B1Qti2BKafB5upnEmeOPl7MG0iMn6zz9DEqs4PNojfi9ShrTKNUYCwK+r+N7si79xziebjqJDtkLxdbP298zDwr53e3r59l6PXvebB7r3cNGPRW4ME9uzcWY9d/Id1UOPQy19uDhYTDMvvnkz9dehqZTJSSYPbyVr4wdL1hhrjj8cn84ubh/dexDs8Y3DwabN/RlqsMNY4uidP+bocdTvVLB7qFIs6PA5by4XfKSSXcT4Gm9YER4Ms4q5k3VbsIwzGa3KI4KGYwWmG1W+RL/OSMe6rKvWJgEd6u35b6IuccYLhj3khdipvNMtekRiKHBjVOXXIaPfYI/r+uDPDf+82Lk7U9Qa7Zb5fsj+5tVLG8yaqzemtLuqA+XIuuPcr6YaPjvv4/7qcnvLVA6FHJz9rzf+TlczRvdG3/pyDGtyU9rykDj3fd5ZhD78efLvqPy7FW1fVfxMOX3N6YuveFq/Dh4cwJB4nCy7E8ZJGz99WY5mgwOZQ6/fTG4Mj3Kyy0PMnMtmFqN8cGh80Zj9BYStSzGy3XfA5E4+Pyfv8jscTXme1djBoP/us2eFW43x5QxYvVnjbc4ahYymKx+Pm76FqOEBdPP02kASgi/2RbycRZttmbMWj8vf9bn17uD+rq0Bt3uuH639qIbpQMWEt00HSxmy/p48pA74r4fWsPBw2S+qo8ajcbjY6Pxk9/1Dso+vVO3CQQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBIJ//AQnPSkBrVysyAAAAAElFTkSuQmCC

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: jain.shrey1110@gmail.com
  facebook:
  flickr:
  github: shreyshah173
  instagram: shreyshah173
  linkedin: shreyshah173
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: shreyshah173
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://shreyshah173.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
